Algoritmo "PAG50_1A"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tayna
// Data atual  : 03/04/2023
Var
// Seção de Declarações das variáveis 
numero, resultado: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
numero<-15
   repita
      resultado<-numero*numero
      escreval(resultado)
      numero<-numero+1
   ate numero>200

Fimalgoritmo