Algoritmo "1_C_divisiveisPor4menorque200"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tayna
// Data atual  : 03/04/2023
var
// Seção de Declarações das variáveis
contador:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
contador<-1
repita
se (contador mod 4 = 0) entao
escreval(contador)
fimse
contador<-contador+1
ate (contador>199)
Fimalgoritmo