Algoritmo "1_E_numerosImpares0a20"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tayna
// Data atual  : 17/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1

para cont de 1 ate 20 faca
     se cont mod 2 = 1 entao
        escreval(cont)
     fimse
fimpara

Fimalgoritmo