Algoritmo "1_F_divisiveisPor4ate200"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Obama
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Tayna
// Data atual  : 17/04/2023
Var
// Seção de Declarações das variáveis 
cont: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
cont <- 1

para cont de 1 ate 200 faca
     se cont mod 4 = 0 entao
        escreva(cont)
     fimse
fimpara

Fimalgoritmo