Algoritmo "Calcula_circulo"
// Disciplina  : [Linguagem e Lógica de Programação com JavaScript]
// Professor   : Obama
// Descrição   : Programa que calcula o valor do circulo
// Autor(a)    : Tayna
// Data atual  : 15/03/2023
Var
// Seção de Declarações das variáveis
raio:real
area:real
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite o raio do circulo")
leia(raio)
area<-PI*raio*raio
escreva ("O valor da área é: ", area)
Fimalgoritmo